name: Generate Sitemap (Exclude /video)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sitemap-generator
        run: npm install -g sitemap-generator-cli

      - name: Generate sitemap-auto.xml (exclude /video)
        run: |
          mkdir -p public
          sitemap-generator "https://harshiksenthil.github.io/myclipblog" \
            --strip-querystring \
            --filepath public/sitemap-auto.xml \
            --exclude-pattern "/video"

      - name: Commit sitemap
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add public/sitemap-auto.xml
          git commit -m "Update sitemap-auto.xml" || echo "No changes"
          git push origin HEAD:main
